server:
  port: 8081

spring:
  # spring ????
  application:
    name: test-station
  # ?????
  datasource:
    username: root
    password: cyhcd5201314
    url: jdbc:mysql://localhost:3306/test_station?serverTimezone=UTC&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????? ?????????
  mapper-locations: classpath:mapper/*.xml
